### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by tiennampham23** [leducthang98/SpringBoot-Backend-BoilderPlate#1]
- File **<b>application.properties</b>** nên đổi thành **application.yml** để có thể sử dụng syntax dạng hierarchical. See more: [Yml vs properties](https://www.baeldung.com/spring-boot-yaml-vs-properties), [spring yaml](https://www.baeldung.com/spring-yaml)
- Nên sử dụng JPA hoặc ít nhất là Hibernate cho việc ORM. Ít nhất là không nên dùng JDBC vì viết code cực, có thể gây ra SQL Injection nếu không viết query tốt, viết code dài. Trong khi JPA cung cấp cho 1 vài interface đã built-in các function sẵn rồi, như findAll, findByOneProperty....Hoặc cũng có thể viết query thuần khi sử dụng JPA bằng @Query. Việc quản lý transaction và session connect đến DB bằng JDBC cũng phải cẩn thận. Trong khi JPA sẽ giúp mình việc đó(Hoặc mình cũng có thể custom được khi sử dụng JPA)
- Nên dùng HTTP_CODE Spring Boot cung cấp luôn, không cần phải define HTTP_CODE ở file **Constant > Error.java**. Link [Spring response status](https://www.baeldung.com/spring-response-status)
- Nên dùng anotation config model, ví dụ @Table, @Schema, @Column, @Id, @ManyToOne...Tránh trường hợp thanh đổi tên biến trong code, hoặc trong SQL sẽ ảnh hưởng đến việc mapping Model và Table trong SQL.
- Nên viết Repository dạng Interface nếu implement JPA, còn nếu viết class thì nên viết 1 interface để sử dụng tính chất của OOP. Giống như đang viết service.
- Viết thêm 1 lớp DTO để transfrom data response. Lớp DTO này có thể có dạng:
```code
class ReponseDTO<T> {
     code: Int,
     data: T,
     message: String,
     version: String
     ....
}
```

**Comment by leducthang98** [comment]
Okie Nam, tớ sẽ sửa lại thành JPA với chuyển cái file .properties thành yml (cái này thì hôm nay mới biết). còn cái ResponseForm thì t có rồi, ở trong Util á ^^. Anw Tks nhé ✌️
